version: '3.8'

services:
  quiz:
    build: .
    container_name: quiz_app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
    volumes:
      - quiz_data:/app
    restart: unless-stopped

volumes:
  quiz_data: